FROM python:3.11-slim-bookworm

# ---------------------------
# System dependencies
# ---------------------------
RUN apt-get update && apt-get install -y \
    git build-essential cmake \
    libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev \
    xvfb x11-xserver-utils libgl1 \
    && rm -rf /var/lib/apt/lists/*

# ---------------------------
# Workspace
# ---------------------------
WORKDIR /workspace

RUN pip install --upgrade pip Cython

# Install Python-RVO2
RUN git clone https://github.com/sybrenstuvel/Python-RVO2.git && \
    cd Python-RVO2 && \
    python setup.py build && \
    python setup.py install

# Install dependencies
RUN pip install dgl \
    torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu \
    gym==0.26.2 matplotlib opencv-python shapely Cython stable-baselines3 \
    PyYAML torchdata==0.8.0 pydantic comet_ml imageio

RUN git clone https://github.com/pali1460/SocNavGym.git

ENV PYTHONPATH="/workspace:${PYTHONPATH}"

# ---------------------------
# Add your application
# ---------------------------
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# ---------------------------
# Add Xvfb startup script
# ---------------------------
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

ENTRYPOINT ["/usr/local/bin/start.sh"]
